package treescript

import (
	"testing"

	"github.com/lcr/navune/internal/lang"
)

func TestParseJSSimple(t *testing.T) {
	src := `import {x} from './dep'
export function add(a, b) {
  if (a > b) {
    return a;
  }
  return b;
}
class Foo {
  bar(x) {
    return x && true ? 1 : 2;
  }
}
`
	p := NewJS()
	res, err := p.Parse("a.js", []byte(src))
	if err != nil {
		t.Fatal(err)
	}
	if res.Lang != lang.JavaScript {
		t.Errorf("lang = %s", res.Lang)
	}
	if len(res.Functions) != 2 {
		t.Fatalf("want 2 functions, got %d", len(res.Functions))
	}
	if res.Functions[0].Name != "add" || res.Functions[0].Complexity != 2 {
		t.Errorf("add: name=%q complexity=%d (want add/2)", res.Functions[0].Name, res.Functions[0].Complexity)
	}
	// bar: 1 base + 1 if? no if; && (1) + ternary (1) = 3
	if res.Functions[1].Name != "bar" || res.Functions[1].Enclosing != "Foo" {
		t.Errorf("bar: name=%q enclosing=%q (want bar/Foo)", res.Functions[1].Name, res.Functions[1].Enclosing)
	}
	if res.Functions[1].Complexity != 3 {
		t.Errorf("bar complexity = %d (want 3)", res.Functions[1].Complexity)
	}
	if len(res.Types) != 1 || res.Types[0].Name != "Foo" || res.Types[0].Abstract {
		t.Errorf("types = %+v", res.Types)
	}
	if len(res.Imports) != 1 || res.Imports[0] != "./dep" {
		t.Errorf("imports = %v", res.Imports)
	}
}

func TestParseTSTypes(t *testing.T) {
	src := `interface I { x: number }
export function f(x: number): number {
  if (x > 2) {
    return 3;
  }
  return x;
}
`
	p := NewTS()
	res, err := p.Parse("a.ts", []byte(src))
	if err != nil {
		t.Fatal(err)
	}
	if len(res.Functions) != 1 {
		t.Fatalf("want 1 function, got %d", len(res.Functions))
	}
	if res.Functions[0].Complexity != 2 {
		t.Errorf("f complexity = %d (want 2)", res.Functions[0].Complexity)
	}
	if len(res.Types) != 1 {
		t.Fatalf("want 1 type (interface), got %+v", res.Types)
	}
	if res.Types[0].Name != "I" || !res.Types[0].Abstract {
		t.Errorf("interface I should be abstract type, got %+v", res.Types[0])
	}
}

func TestNestedClosureIsSeparateUnit(t *testing.T) {
	src := `export function outer() {
  const inner = (a) => {
    if (a) { console.log(a); }
    return a ? 1 : 2;
  };
  return inner;
}
`
	res, err := NewJS().Parse("a.js", []byte(src))
	if err != nil {
		t.Fatal(err)
	}
	if len(res.Functions) != 2 {
		t.Fatalf("closures are separate units (ADR 0015): want 2 fn, got %d", len(res.Functions))
	}
	if res.Functions[0].Complexity != 1 {
		t.Errorf("outer complexity should be 1 (closure skipped), got %d", res.Functions[0].Complexity)
	}
	anon := res.Functions[1]
	if !anon.Anonymous {
		t.Errorf("second function should be anonymous, got %q", anon.Name)
	}
	if anon.Complexity != 3 { // base + if + ternary
		t.Errorf("closure complexity want 3 got %d", anon.Complexity)
	}
	if anon.Params != 1 {
		t.Errorf("closure params want 1 got %d", anon.Params)
	}
}

func TestExtendedMeasures(t *testing.T) {
	src := `// a significant comment
// *****
export function complex(a, b, n) {
  if (a && b) {
    for (let i = 0; i < n; i++) {
      if (i > 1) { return i; }
    }
  } else if (b) {
    return 1;
  } else {
    return 2;
  }
  return 0;
}
function rec(n) {
  if (n <= 1) { return n; }
  return rec(n - 1);
}
`
	res, err := NewJS().Parse("a.js", []byte(src))
	if err != nil {
		t.Fatal(err)
	}
	byName := map[string]lang.Function{}
	for _, f := range res.Functions {
		byName[f.Name] = f
	}
	cx := byName["complex"]
	if cx.Params != 3 {
		t.Errorf("params want 3 got %d", cx.Params)
	}
	// if(+1) + &&(+1) + for(+2) + inner if(+3) + else-if(+1) + else(+1) = 9
	if cx.Cognitive != 9 {
		t.Errorf("cognitive want 9 got %d", cx.Cognitive)
	}
	if cx.Nesting != 3 {
		t.Errorf("nesting want 3 got %d", cx.Nesting)
	}
	rec := byName["rec"]
	if rec.Cognitive != 2 {
		t.Errorf("rec cognitive want 2 got %d", rec.Cognitive)
	}
	if len(rec.Calls) != 1 || rec.Calls[0] != "rec" {
		t.Errorf("rec calls want [rec], got %v", rec.Calls)
	}
	if res.CommentLines != 1 {
		t.Errorf("comment lines want 1 got %d", res.CommentLines)
	}
}

func TestGeneratedCommentDetection(t *testing.T) {
	// generated markers are not in the element model for ts; a plain parse works
	src := `// Code generated by foo. DO NOT EDIT.
export const a = 1;
`
	res, err := NewJS().Parse("a.js", []byte(src))
	if err != nil {
		t.Fatal(err)
	}
	if res.PhysicalSLOC == 0 {
		t.Errorf("physical sloc should count code line")
	}
}
