package treescript

import (
	"testing"

	"github.com/lcr/navune/internal/lang"
)

func TestParseJSSimple(t *testing.T) {
	src := `import {x} from './dep'
export function add(a, b) {
  if (a > b) {
    return a;
  }
  return b;
}
class Foo {
  bar(x) {
    return x && true ? 1 : 2;
  }
}
`
	p := NewJS()
	res, err := p.Parse("a.js", []byte(src))
	if err != nil {
		t.Fatal(err)
	}
	if res.Lang != lang.JavaScript {
		t.Errorf("lang = %s", res.Lang)
	}
	if len(res.Functions) != 2 {
		t.Fatalf("want 2 functions, got %d", len(res.Functions))
	}
	if res.Functions[0].Name != "add" || res.Functions[0].Complexity != 2 {
		t.Errorf("add: name=%q complexity=%d (want add/2)", res.Functions[0].Name, res.Functions[0].Complexity)
	}
	// bar: 1 base + 1 if? no if; && (1) + ternary (1) = 3
	if res.Functions[1].Name != "bar" || res.Functions[1].Enclosing != "Foo" {
		t.Errorf("bar: name=%q enclosing=%q (want bar/Foo)", res.Functions[1].Name, res.Functions[1].Enclosing)
	}
	if res.Functions[1].Complexity != 3 {
		t.Errorf("bar complexity = %d (want 3)", res.Functions[1].Complexity)
	}
	if len(res.Types) != 1 || res.Types[0].Name != "Foo" || res.Types[0].Abstract {
		t.Errorf("types = %+v", res.Types)
	}
	if len(res.Imports) != 1 || res.Imports[0] != "./dep" {
		t.Errorf("imports = %v", res.Imports)
	}
}

func TestParseTSTypes(t *testing.T) {
	src := `interface I { x: number }
export function f(x: number): number {
  if (x > 2) {
    return 3;
  }
  return x;
}
`
	p := NewTS()
	res, err := p.Parse("a.ts", []byte(src))
	if err != nil {
		t.Fatal(err)
	}
	if len(res.Functions) != 1 {
		t.Fatalf("want 1 function, got %d", len(res.Functions))
	}
	if res.Functions[0].Complexity != 2 {
		t.Errorf("f complexity = %d (want 2)", res.Functions[0].Complexity)
	}
	if len(res.Types) != 1 {
		t.Fatalf("want 1 type (interface), got %+v", res.Types)
	}
	if res.Types[0].Name != "I" || !res.Types[0].Abstract {
		t.Errorf("interface I should be abstract type, got %+v", res.Types[0])
	}
}

func TestNestedClosureDoesNotInflate(t *testing.T) {
	src := `export function outer() {
  const inner = (a) => {
    if (a) { console.log(a); }
    return a ? 1 : 2;
  };
  return inner;
}
`
	res, err := NewJS().Parse("a.js", []byte(src))
	if err != nil {
		t.Fatal(err)
	}
	if len(res.Functions) != 1 {
		t.Fatalf("closures are not separate units: want 1 fn, got %d", len(res.Functions))
	}
	if res.Functions[0].Complexity != 1 {
		t.Errorf("outer complexity should be 1 (closure skipped), got %d", res.Functions[0].Complexity)
	}
}

func TestGeneratedCommentDetection(t *testing.T) {
	// generated markers are not in the element model for ts; a plain parse works
	src := `// Code generated by foo. DO NOT EDIT.
export const a = 1;
`
	res, err := NewJS().Parse("a.js", []byte(src))
	if err != nil {
		t.Fatal(err)
	}
	if res.PhysicalSLOC == 0 {
		t.Errorf("physical sloc should count code line")
	}
}
