// Package java provides a tree-sitter adapter for Java. It maps the grammar's
// concrete syntax tree onto Navune's uniform element model. Requires cgo.
package java

import (
	"fmt"
	"strings"
	"unicode"

	sitter "github.com/tree-sitter/go-tree-sitter"
	tsjava "github.com/tree-sitter/tree-sitter-java/bindings/go"

	"github.com/lcr/navune/internal/lang"
)

// Parser adapts Java (.java).
type Parser struct{}

// New returns a parser for Java.
func New() *Parser { return &Parser{} }

// Lang implements lang.Parser.
func (p *Parser) Lang() lang.Lang { return lang.Java }

// Extensions implements lang.Parser.
func (p *Parser) Extensions() []string { return []string{".java"} }

// Parse parses a single Java source file into the element model.
func (p *Parser) Parse(path string, src []byte) (*lang.FileResult, error) {
	par := sitter.NewParser()
	if err := par.SetLanguage(sitter.NewLanguage(tsjava.Language())); err != nil {
		return nil, err
	}
	tree := par.Parse(src, nil)
	if tree == nil || tree.RootNode() == nil {
		return nil, fmt.Errorf("parse %s: no syntax tree", path)
	}
	res := &lang.FileResult{
		Path:       path,
		Lang:       lang.Java,
		Class:      lang.Prod,
		TotalLines: countLines(src),
	}
	if generatedMarker(tree.RootNode(), src) {
		res.MarkGenerated()
	}
	w := &walker{res: res, src: src}
	w.walk(tree.RootNode())
	res.PhysicalSLOC = len(w.lines)
	res.LogicalLOC = w.logical
	return res, nil
}

// generatedMarker reports whether the file is generated: a "Code generated …
// DO NOT EDIT." / @generated / <auto-generated> comment, or an @Generated
// annotation.
func generatedMarker(root *sitter.Node, src []byte) bool {
	var scan func(n *sitter.Node) bool
	scan = func(n *sitter.Node) bool {
		switch n.Kind() {
		case "line_comment", "block_comment":
			if hasGeneratedComment(string(src[n.StartByte():n.EndByte()])) {
				return true
			}
		case "marker_annotation", "annotation":
			if nm := n.ChildByFieldName("name"); nm != nil && string(src[nm.StartByte():nm.EndByte()]) == "Generated" {
				return true
			}
		}
		for i := uint(0); i < n.NamedChildCount(); i++ {
			if scan(n.NamedChild(i)) {
				return true
			}
		}
		return false
	}
	return scan(root)
}

func hasGeneratedComment(text string) bool {
	if strings.Contains(text, "Code generated") && strings.Contains(text, "DO NOT EDIT") {
		return true
	}
	low := strings.ToLower(text)
	return strings.Contains(low, "@generated") || strings.Contains(low, "<auto-generated>")
}

var nameKinds = map[string]bool{
	"identifier":      true,
	"type_identifier": true,
}

var commentKinds = map[string]bool{
	"line_comment":  true,
	"block_comment": true,
}

var stringLike = map[string]bool{
	"string_literal":    true,
	"character_literal": true,
}

var numberKinds = map[string]bool{
	"decimal_integer_literal":        true,
	"hex_integer_literal":            true,
	"octal_integer_literal":          true,
	"binary_integer_literal":         true,
	"decimal_floating_point_literal": true,
	"hex_floating_point_literal":     true,
}

var typeKinds = map[string]bool{
	"class_declaration":           true,
	"interface_declaration":       true,
	"enum_declaration":            true,
	"record_declaration":          true,
	"annotation_type_declaration": true,
}

// decisionKinds add +1 cyclomatic complexity each; switch cases are counted
// separately via switch_label (ADR 0019).
var decisionKinds = map[string]bool{
	"if_statement":           true,
	"for_statement":          true,
	"enhanced_for_statement": true,
	"while_statement":        true,
	"do_statement":           true,
	"catch_clause":           true,
	"ternary_expression":     true,
}

func isLogicalNode(kind string) bool {
	if strings.HasSuffix(kind, "_statement") {
		return true
	}
	switch kind {
	case "class_declaration", "interface_declaration", "enum_declaration",
		"record_declaration", "annotation_type_declaration",
		"method_declaration", "constructor_declaration", "compact_constructor_declaration",
		"field_declaration", "local_variable_declaration",
		"import_declaration", "package_declaration":
		return true
	}
	return false
}

type walker struct {
	res      *lang.FileResult
	src      []byte
	lines    map[int]bool
	comments map[int]bool
	logical  int
	funcs    []*lang.Function
}

func (w *walker) walk(root *sitter.Node) {
	w.lines = map[int]bool{}
	w.comments = map[int]bool{}
	w.walkNode(root, nil, "")
	for _, f := range w.funcs {
		f.Length = w.codeLinesBetween(f.StartLine, f.EndLine)
		w.res.Functions = append(w.res.Functions, *f)
	}
	w.res.CommentLines = len(w.comments)
}

func (w *walker) codeLinesBetween(start, end int) int {
	n := 0
	for l := start; l <= end; l++ {
		if w.lines[l] {
			n++
		}
	}
	return n
}

func (w *walker) walkNode(n *sitter.Node, fn *lang.Function, typeName string) {
	kind := n.Kind()
	if commentKinds[kind] {
		w.recordComment(n)
		return
	}
	if stringLike[kind] {
		w.emitToken(lang.Token{Kind: lang.TokString, Text: "STR", Line: startLine(n)})
		return
	}
	if numberKinds[kind] {
		w.emitToken(lang.Token{Kind: lang.TokNumber, Text: "NUM", Line: startLine(n)})
		return
	}

	if isLogicalNode(kind) {
		w.logical++
	}

	if kind == "package_declaration" {
		w.res.Package = clauseText(w.text(n), "package")
	}
	if kind == "import_declaration" {
		if imp := importText(w.text(n)); imp != "" {
			w.res.Imports = append(w.res.Imports, imp)
		}
	}

	if typeKinds[kind] {
		name := w.nameOf(n)
		if name != "" {
			w.res.Types = append(w.res.Types, lang.TypeDecl{Name: name, Abstract: isAbstractType(n, kind)})
		}
		next := name
		if next == "" {
			next = typeName
		}
		for i := uint(0); i < n.NamedChildCount(); i++ {
			w.walkNode(n.NamedChild(i), fn, next)
		}
		return
	}

	switch kind {
	case "method_declaration", "constructor_declaration", "compact_constructor_declaration":
		w.addFunction(n, typeName, false)
		return
	case "lambda_expression":
		w.addFunction(n, typeName, true)
		return
	}

	if fn != nil {
		if decisionKinds[kind] {
			fn.Complexity++
		}
		if kind == "switch_label" && strings.HasPrefix(strings.TrimSpace(w.text(n)), "case") {
			fn.Complexity++
		}
		if kind == "binary_expression" && hasLeafToken(n, "&&", "||") {
			fn.Complexity++
		}
	}
	w.children(n, fn, typeName)
}

func (w *walker) addFunction(n *sitter.Node, typeName string, isLambda bool) {
	start := startLine(n)
	name := w.nameOf(n)
	if isLambda || name == "" {
		name = fmt.Sprintf("<anonymous@%d>", start)
	}
	f := &lang.Function{
		Name:       name,
		Enclosing:  typeName,
		Anonymous:  isLambda,
		Complexity: 1,
		StartLine:  start,
		EndLine:    int(n.EndPosition().Row) + 1,
		Params:     w.paramsOf(n),
	}
	self := ""
	if !isLambda {
		self = name
	}
	f.Cognitive, f.Nesting, f.BoolMax, f.Calls = w.analyzeBody(w.bodyOf(n), self)
	w.funcs = append(w.funcs, f)
	w.children(n, f, typeName)
}

func (w *walker) nameOf(n *sitter.Node) string {
	if nm := n.ChildByFieldName("name"); nm != nil {
		return w.text(nm)
	}
	return ""
}

func (w *walker) bodyOf(n *sitter.Node) *sitter.Node {
	if b := n.ChildByFieldName("body"); b != nil {
		return b
	}
	// expression-bodied lambda: the body is the trailing expression.
	if n.NamedChildCount() > 0 {
		return n.NamedChild(n.NamedChildCount() - 1)
	}
	return nil
}

func (w *walker) paramsOf(n *sitter.Node) int {
	pl := n.ChildByFieldName("parameters")
	if pl == nil {
		return 0
	}
	cnt := 0
	for i := uint(0); i < pl.NamedChildCount(); i++ {
		if pl.NamedChild(i).Kind() == "comment" {
			continue
		}
		cnt++
	}
	return cnt
}

// isAbstractType reports interfaces (and annotation types) plus classes
// declared `abstract` (ADR 0019).
func isAbstractType(n *sitter.Node, kind string) bool {
	if kind == "interface_declaration" || kind == "annotation_type_declaration" {
		return true
	}
	if m := findKind(n, "modifiers"); m != nil {
		for i := uint(0); i < m.ChildCount(); i++ {
			if m.Child(i).Kind() == "abstract" {
				return true
			}
		}
	}
	return false
}

func clauseText(text, keyword string) string {
	s := strings.TrimSpace(text)
	s = strings.TrimPrefix(s, keyword)
	s = strings.TrimSpace(s)
	s = strings.TrimSuffix(s, ";")
	return strings.TrimSpace(s)
}

func importText(text string) string {
	s := strings.TrimSpace(text)
	s = strings.TrimPrefix(s, "import")
	s = strings.TrimSpace(s)
	s = strings.TrimPrefix(s, "static")
	s = strings.TrimSpace(s)
	s = strings.TrimSuffix(s, ";")
	return strings.TrimSpace(s)
}

// analyzeBody computes cognitive complexity, nesting, boolean-condition max,
// and direct callees (ADR 0015).
func (w *walker) analyzeBody(body *sitter.Node, self string) (cognitive, nesting, boolMax int, calls []string) {
	if body == nil {
		return 0, 0, 0, nil
	}
	c := &cogWalk{w: w, self: self}
	c.node(body, "")
	c.cognitive += c.logical + c.recursion
	return c.cognitive, c.maxDepth, c.boolMax, c.calls
}

type cogWalk struct {
	w         *walker
	cognitive int
	depth     int
	maxDepth  int
	boolMax   int
	self      string
	calls     []string
	recursion int
	logical   int
}

func (c *cogWalk) nest(n *sitter.Node) {
	if n == nil {
		return
	}
	c.depth++
	if c.depth > c.maxDepth {
		c.maxDepth = c.depth
	}
	c.node(n, "")
	c.depth--
}

func sameNode(a, b *sitter.Node) bool {
	return a != nil && b != nil && a.StartByte() == b.StartByte() && a.EndByte() == b.EndByte()
}

func (c *cogWalk) walkChildren(n *sitter.Node, inh string) {
	for i := uint(0); i < n.NamedChildCount(); i++ {
		c.node(n.NamedChild(i), inh)
	}
}

func (c *cogWalk) walkOthers(n, body *sitter.Node) {
	for i := uint(0); i < n.NamedChildCount(); i++ {
		ch := n.NamedChild(i)
		if sameNode(ch, body) {
			continue
		}
		c.node(ch, "")
	}
}

func (c *cogWalk) node(n *sitter.Node, inh string) {
	if n == nil {
		return
	}
	switch n.Kind() {
	case "method_declaration", "constructor_declaration", "compact_constructor_declaration",
		"lambda_expression", "class_declaration", "interface_declaration",
		"enum_declaration", "record_declaration", "annotation_type_declaration":
		return // separate function/type unit
	case "if_statement":
		c.cognitive += 1 + c.depth
		c.nest(n.ChildByFieldName("consequence"))
		if alt := n.ChildByFieldName("alternative"); alt != nil {
			c.elseClause(alt)
		}
		c.node(n.ChildByFieldName("condition"), "")
		return
	case "for_statement", "enhanced_for_statement", "while_statement", "do_statement":
		c.cognitive += 1 + c.depth
		body := n.ChildByFieldName("body")
		c.nest(body)
		c.walkOthers(n, body)
		return
	case "switch_expression", "switch_statement":
		c.cognitive += 1 + c.depth
		body := n.ChildByFieldName("body")
		c.nest(body)
		c.walkOthers(n, body)
		return
	case "catch_clause":
		c.cognitive += 1 + c.depth
		body := n.ChildByFieldName("body")
		c.nest(body)
		c.walkOthers(n, body)
		return
	case "ternary_expression":
		c.cognitive += 1 + c.depth
		for i := uint(0); i < n.NamedChildCount(); i++ {
			c.nest(n.NamedChild(i))
		}
		return
	case "binary_expression":
		op := c.w.binaryOp(n)
		if op == "&&" || op == "||" {
			if op != inh {
				c.logical++
				if cnt := c.boolOperands(n); cnt > c.boolMax {
					c.boolMax = cnt
				}
			}
			inh = op
		} else {
			inh = ""
		}
		c.walkChildren(n, inh)
		return
	case "method_invocation":
		if name := c.w.calleeName(n); name != "" {
			c.calls = append(c.calls, name)
			if c.self != "" && name == c.self {
				c.recursion++
			}
		}
		c.walkChildren(n, "")
		return
	}
	c.walkChildren(n, inh)
}

func (c *cogWalk) elseClause(alt *sitter.Node) {
	if alt == nil {
		return
	}
	if alt.Kind() == "if_statement" {
		c.cognitive++
		c.nest(alt.ChildByFieldName("consequence"))
		if a := alt.ChildByFieldName("alternative"); a != nil {
			c.elseClause(a)
		}
		c.node(alt.ChildByFieldName("condition"), "")
		return
	}
	c.cognitive++
	c.nest(alt)
}

func (w *walker) binaryOp(n *sitter.Node) string {
	for i := uint(0); i < n.ChildCount(); i++ {
		ch := n.Child(i)
		if !ch.IsNamed() && ch.ChildCount() == 0 {
			if ch.Kind() == "&&" || ch.Kind() == "||" {
				return ch.Kind()
			}
		}
	}
	return ""
}

func (w *walker) calleeName(n *sitter.Node) string {
	nm := n.ChildByFieldName("name")
	if nm == nil {
		return ""
	}
	switch nm.Kind() {
	case "identifier", "field_identifier":
		return w.text(nm)
	}
	return ""
}

func (c *cogWalk) boolOperands(n *sitter.Node) int {
	if n == nil || n.Kind() != "binary_expression" {
		return 1
	}
	op := c.w.binaryOp(n)
	if op != "&&" && op != "||" {
		return 1
	}
	left := n.ChildByFieldName("left")
	right := n.ChildByFieldName("right")
	if left == nil && n.NamedChildCount() > 0 {
		left = n.NamedChild(0)
	}
	if right == nil && n.NamedChildCount() > 1 {
		right = n.NamedChild(1)
	}
	return c.boolOperands(left) + c.boolOperands(right)
}

func (w *walker) recordComment(n *sitter.Node) {
	start := startLine(n)
	for i, line := range strings.Split(w.text(n), "\n") {
		if isSignificantComment(line) {
			w.comments[start+i] = true
		}
	}
}

func isSignificantComment(text string) bool {
	for _, r := range text {
		if unicode.IsLetter(r) || unicode.IsDigit(r) {
			return true
		}
	}
	return false
}

func (w *walker) children(n *sitter.Node, fn *lang.Function, typeName string) {
	for i := uint(0); i < n.ChildCount(); i++ {
		c := n.Child(i)
		if c.ChildCount() == 0 {
			w.emitLeaf(c)
			continue
		}
		w.walkNode(c, fn, typeName)
	}
}

func (w *walker) emitLeaf(n *sitter.Node) {
	kind := n.Kind()
	if commentKinds[kind] {
		w.recordComment(n)
		return
	}
	if stringLike[kind] {
		return
	}
	if numberKinds[kind] {
		w.emitToken(lang.Token{Kind: lang.TokNumber, Text: "NUM", Line: startLine(n)})
		return
	}
	t := lang.Token{Line: startLine(n)}
	if nameKinds[kind] {
		t.Kind = lang.TokIdent
		t.Text = w.text(n)
	} else {
		t.Kind = lang.TokKeyword
		t.Text = w.text(n)
	}
	w.emitToken(t)
}

func (w *walker) text(n *sitter.Node) string {
	return string(w.src[n.StartByte():n.EndByte()])
}

func (w *walker) emitToken(t lang.Token) {
	w.res.Tokens = append(w.res.Tokens, t)
	w.lines[t.Line] = true
}

func hasLeafToken(n *sitter.Node, kinds ...string) bool {
	for i := uint(0); i < n.ChildCount(); i++ {
		c := n.Child(i)
		if !c.IsNamed() && c.ChildCount() == 0 {
			for _, k := range kinds {
				if c.Kind() == k {
					return true
				}
			}
		}
	}
	return false
}

func findKind(n *sitter.Node, kind string) *sitter.Node {
	if n.Kind() == kind {
		return n
	}
	for i := uint(0); i < n.NamedChildCount(); i++ {
		if found := findKind(n.NamedChild(i), kind); found != nil {
			return found
		}
	}
	return nil
}

func startLine(n *sitter.Node) int { return int(n.StartPosition().Row) + 1 }

func countLines(src []byte) int {
	if len(src) == 0 {
		return 0
	}
	n := strings.Count(string(src), "\n")
	if src[len(src)-1] != '\n' {
		n++
	}
	return n
}
