package golang

import (
	"testing"

	"github.com/lcr/navune/internal/lang"
)

func TestParseBasics(t *testing.T) {
	src := `package demo

import "fmt"

// Foo is a doc comment
type Foo struct{}

type Greeter interface {
	Greet() string
}

func Add(a, b int) int {
	if a > b {
		return a
	}
	return b
}

func main() {
	for i := 0; i < 3; i++ {
		fmt.Println(i)
	}
}
`
	p := New()
	res, err := p.Parse("demo.go", []byte(src))
	if err != nil {
		t.Fatal(err)
	}
	if res.Package != "demo" {
		t.Errorf("package want demo got %s", res.Package)
	}
	if len(res.Types) != 2 {
		t.Fatalf("want 2 types (struct + interface), got %d", len(res.Types))
	}
	// interface is abstract
	if !res.Types[1].Abstract {
		t.Errorf("Greeter should be abstract (interface)")
	}
	if len(res.Functions) != 2 {
		t.Fatalf("want 2 functions, got %d", len(res.Functions))
	}
	// Add: base 1 + 1 if = 2. main: base 1 + for = 2.
	if res.Functions[0].Complexity != 2 {
		t.Errorf("Add complexity want 2, got %d", res.Functions[0].Complexity)
	}
	if res.Functions[1].Complexity != 2 {
		t.Errorf("main complexity want 2, got %d", res.Functions[1].Complexity)
	}
	if len(res.Imports) != 1 || res.Imports[0] != "fmt" {
		t.Errorf("imports want [fmt], got %v", res.Imports)
	}
}

func TestComplexityLogicOperators(t *testing.T) {
	src := `package x

func f(a, b, c bool) bool {
	if a && b || c {
		return true
	}
	return false
}
`
	res, err := New().Parse("x.go", []byte(src))
	if err != nil {
		t.Fatal(err)
	}
	// 1 base + 1 if + 1 && + 1 || = 4
	if got := res.Functions[0].Complexity; got != 4 {
		t.Errorf("complexity want 4 got %d", got)
	}
}

func TestNestedClosureDoesNotInflateParent(t *testing.T) {
	src := `package x

func outer() {
	inner := func() {
		if true {
			println("y")
		}
	}
	_ = inner
}
`
	res, err := New().Parse("x.go", []byte(src))
	if err != nil {
		t.Fatal(err)
	}
	if len(res.Functions) != 1 {
		t.Fatalf("closures are not separate v1 functions, want 1, got %d", len(res.Functions))
	}
	if res.Functions[0].Complexity != 1 {
		t.Errorf("outer complexity want 1 (closure skipped), got %d", res.Functions[0].Complexity)
	}
}

func TestGeneratedMarker(t *testing.T) {
	src := `// Code generated by tool. DO NOT EDIT.

package x
func f() {}
`
	res, err := New().Parse("x.go", []byte(src))
	if err != nil {
		t.Fatal(err)
	}
	if !res.IsGenerated() {
		t.Error("should be marked generated")
	}
}

func TestTokensNormalizeLiteralsKeepIdents(t *testing.T) {
	src := `package x
func f() {
	a := "hello"
	b := 42
	c := a
	_ = b
	_ = c
}
`
	res, err := New().Parse("x.go", []byte(src))
	if err != nil {
		t.Fatal(err)
	}
	var strs, nums int
	for _, tok := range res.Tokens {
		switch tok.Kind {
		case lang.TokString:
			strs++
			if tok.Text != "STR" {
				t.Errorf("string literal should normalize to STR, got %q", tok.Text)
			}
		case lang.TokNumber:
			nums++
			if tok.Text != "NUM" {
				t.Errorf("number should normalize to NUM, got %q", tok.Text)
			}
		}
	}
	if strs != 1 || nums != 1 {
		t.Errorf("want 1 string + 1 number token, got %d + %d", strs, nums)
	}
	hasIdent := false
	for _, tok := range res.Tokens {
		if tok.Kind == lang.TokIdent && tok.Text == "hello" {
			hasIdent = true
		}
	}
	// identifier 'hello' is inside a string literal so must NOT appear
	if hasIdent {
		t.Error("string contents must not leak into the token stream")
	}
}
