// Package rust provides a tree-sitter adapter for Rust. It maps the grammar's
// concrete syntax tree onto Navune's uniform element model. Requires cgo.
package rust

import (
	"fmt"
	"strings"
	"unicode"

	sitter "github.com/tree-sitter/go-tree-sitter"
	tsrust "github.com/tree-sitter/tree-sitter-rust/bindings/go"

	"github.com/lcr/navune/internal/lang"
)

// Parser adapts Rust (.rs).
type Parser struct{}

// New returns a parser for Rust.
func New() *Parser { return &Parser{} }

// Lang implements lang.Parser.
func (p *Parser) Lang() lang.Lang { return lang.Rust }

// Extensions implements lang.Parser.
func (p *Parser) Extensions() []string { return []string{".rs"} }

// Parse parses a single Rust source file into the element model.
func (p *Parser) Parse(path string, src []byte) (*lang.FileResult, error) {
	par := sitter.NewParser()
	if err := par.SetLanguage(sitter.NewLanguage(tsrust.Language())); err != nil {
		return nil, err
	}
	tree := par.Parse(src, nil)
	if tree == nil || tree.RootNode() == nil {
		return nil, fmt.Errorf("parse %s: no syntax tree", path)
	}
	res := &lang.FileResult{
		Path:       path,
		Lang:       lang.Rust,
		Class:      lang.Prod,
		TotalLines: countLines(src),
	}
	if generatedMarker(tree.RootNode(), src) {
		res.MarkGenerated()
	}
	w := &walker{res: res, src: src}
	w.walk(tree.RootNode())
	res.PhysicalSLOC = len(w.lines)
	res.LogicalLOC = w.logical
	return res, nil
}

// generatedMarker reports whether the file is generated: a "Code generated …
// DO NOT EDIT." / @generated / <auto-generated> comment.
func generatedMarker(root *sitter.Node, src []byte) bool {
	var scan func(n *sitter.Node) bool
	scan = func(n *sitter.Node) bool {
		switch n.Kind() {
		case "line_comment", "block_comment":
			if hasGeneratedComment(string(src[n.StartByte():n.EndByte()])) {
				return true
			}
		}
		for i := uint(0); i < n.NamedChildCount(); i++ {
			if scan(n.NamedChild(i)) {
				return true
			}
		}
		return false
	}
	return scan(root)
}

func hasGeneratedComment(text string) bool {
	if strings.Contains(text, "Code generated") && strings.Contains(text, "DO NOT EDIT") {
		return true
	}
	low := strings.ToLower(text)
	return strings.Contains(low, "@generated") || strings.Contains(low, "<auto-generated>")
}

var nameKinds = map[string]bool{
	"identifier":       true,
	"type_identifier":  true,
	"field_identifier": true,
}

var commentKinds = map[string]bool{
	"line_comment":  true,
	"block_comment": true,
}

var stringLike = map[string]bool{
	"string_literal":     true,
	"raw_string_literal": true,
	"char_literal":       true,
}

var numberKinds = map[string]bool{
	"integer_literal": true,
	"float_literal":   true,
}

var typeKinds = map[string]bool{
	"struct_item": true,
	"enum_item":   true,
	"trait_item":  true,
	"union_item":  true,
}

// decisionKinds add +1 cyclomatic complexity each; match arms and the `?`
// operator are counted separately (ADR 0019).
var decisionKinds = map[string]bool{
	"if_expression":    true,
	"while_expression": true,
	"loop_expression":  true,
	"for_expression":   true,
}

func isLogicalNode(kind string) bool {
	switch kind {
	case "function_item", "struct_item", "enum_item", "trait_item", "union_item",
		"impl_item", "mod_item", "use_declaration", "extern_crate_declaration",
		"let_declaration", "const_item", "static_item", "type_item",
		"expression_statement", "macro_invocation", "foreign_mod_item",
		"function_signature_item":
		return true
	}
	return false
}

type walker struct {
	res      *lang.FileResult
	src      []byte
	lines    map[int]bool
	comments map[int]bool
	logical  int
	funcs    []*lang.Function
}

func (w *walker) walk(root *sitter.Node) {
	w.lines = map[int]bool{}
	w.comments = map[int]bool{}
	w.walkNode(root, nil, "")
	for _, f := range w.funcs {
		f.Length = w.codeLinesBetween(f.StartLine, f.EndLine)
		w.res.Functions = append(w.res.Functions, *f)
	}
	w.res.CommentLines = len(w.comments)
}

func (w *walker) codeLinesBetween(start, end int) int {
	n := 0
	for l := start; l <= end; l++ {
		if w.lines[l] {
			n++
		}
	}
	return n
}

func (w *walker) walkNode(n *sitter.Node, fn *lang.Function, typeName string) {
	kind := n.Kind()
	if commentKinds[kind] {
		w.recordComment(n)
		return
	}
	if stringLike[kind] {
		w.emitToken(lang.Token{Kind: lang.TokString, Text: "STR", Line: startLine(n)})
		return
	}
	if numberKinds[kind] {
		w.emitToken(lang.Token{Kind: lang.TokNumber, Text: "NUM", Line: startLine(n)})
		return
	}

	if isLogicalNode(kind) {
		w.logical++
	}

	switch kind {
	case "use_declaration":
		if imp := w.useText(n); imp != "" {
			w.res.Imports = append(w.res.Imports, imp)
		}
	case "extern_crate_declaration":
		if nm := n.ChildByFieldName("name"); nm != nil {
			w.res.Imports = append(w.res.Imports, "extern:"+w.text(nm))
		}
	case "mod_item":
		if n.ChildByFieldName("body") == nil {
			if nm := n.ChildByFieldName("name"); nm != nil {
				w.res.Imports = append(w.res.Imports, "mod:"+w.text(nm))
			}
		}
	}

	if typeKinds[kind] {
		name := w.nameOf(n)
		if name != "" {
			w.res.Types = append(w.res.Types, lang.TypeDecl{Name: name, Abstract: kind == "trait_item"})
		}
		next := name
		if next == "" {
			next = typeName
		}
		for i := uint(0); i < n.NamedChildCount(); i++ {
			w.walkNode(n.NamedChild(i), fn, next)
		}
		return
	}

	if kind == "impl_item" {
		next := implTypeName(w.text(n.ChildByFieldName("type")))
		if next == "" {
			next = typeName
		}
		for i := uint(0); i < n.NamedChildCount(); i++ {
			w.walkNode(n.NamedChild(i), fn, next)
		}
		return
	}

	switch kind {
	case "function_item":
		w.addFunction(n, typeName, false)
		return
	case "closure_expression":
		w.addFunction(n, typeName, true)
		return
	}

	if fn != nil {
		if decisionKinds[kind] {
			fn.Complexity++
		}
		if kind == "try_expression" {
			fn.Complexity++
		}
		if kind == "match_expression" {
			if arms := matchArmCount(n); arms > 1 {
				fn.Complexity += arms - 1
			}
		}
		if kind == "binary_expression" && hasLeafToken(n, "&&", "||") {
			fn.Complexity++
		}
	}
	w.children(n, fn, typeName)
}

// matchArmCount counts the arms of a match expression's block.
func matchArmCount(n *sitter.Node) int {
	body := n.ChildByFieldName("body")
	if body == nil {
		return 0
	}
	cnt := 0
	for i := uint(0); i < body.NamedChildCount(); i++ {
		if body.NamedChild(i).Kind() == "match_arm" {
			cnt++
		}
	}
	return cnt
}

func (w *walker) addFunction(n *sitter.Node, typeName string, isClosure bool) {
	start := startLine(n)
	name := w.nameOf(n)
	if isClosure || name == "" {
		name = fmt.Sprintf("<anonymous@%d>", start)
	}
	f := &lang.Function{
		Name:       name,
		Enclosing:  typeName,
		Anonymous:  isClosure,
		Complexity: 1,
		StartLine:  start,
		EndLine:    int(n.EndPosition().Row) + 1,
		Params:     w.paramsOf(n),
	}
	self := ""
	if !isClosure {
		self = name
	}
	f.Cognitive, f.Nesting, f.BoolMax, f.Calls = w.analyzeBody(n.ChildByFieldName("body"), self)
	w.funcs = append(w.funcs, f)
	w.children(n, f, typeName)
}

func (w *walker) nameOf(n *sitter.Node) string {
	if nm := n.ChildByFieldName("name"); nm != nil {
		return w.text(nm)
	}
	return ""
}

// implTypeName reduces an impl target to its base type name: Foo<T> -> Foo,
// path::Foo -> Foo.
func implTypeName(s string) string {
	s = strings.TrimSpace(s)
	if i := strings.IndexByte(s, '<'); i >= 0 {
		s = s[:i]
	}
	if i := strings.LastIndex(s, "::"); i >= 0 {
		s = s[i+2:]
	}
	return strings.TrimSpace(s)
}

func (w *walker) paramsOf(n *sitter.Node) int {
	pl := n.ChildByFieldName("parameters")
	if pl == nil {
		return 0
	}
	cnt := 0
	for i := uint(0); i < pl.NamedChildCount(); i++ {
		switch pl.NamedChild(i).Kind() {
		case "parameter", "variadic_parameter":
			cnt++
		}
	}
	return cnt
}

// useText extracts the module path from a use declaration, e.g.
// `use crate::a::b;` -> "crate::a::b".
func (w *walker) useText(n *sitter.Node) string {
	if arg := n.ChildByFieldName("argument"); arg != nil {
		return w.text(arg)
	}
	s := strings.TrimSpace(w.text(n))
	s = strings.TrimPrefix(s, "use")
	s = strings.TrimSuffix(strings.TrimSpace(s), ";")
	return strings.TrimSpace(s)
}

// analyzeBody computes cognitive complexity, nesting, boolean-condition max,
// and direct callees (ADR 0015).
func (w *walker) analyzeBody(body *sitter.Node, self string) (cognitive, nesting, boolMax int, calls []string) {
	if body == nil {
		return 0, 0, 0, nil
	}
	c := &cogWalk{w: w, self: self}
	c.node(body, "")
	c.cognitive += c.logical + c.recursion
	return c.cognitive, c.maxDepth, c.boolMax, c.calls
}

type cogWalk struct {
	w         *walker
	cognitive int
	depth     int
	maxDepth  int
	boolMax   int
	self      string
	calls     []string
	recursion int
	logical   int
}

func (c *cogWalk) nest(n *sitter.Node) {
	if n == nil {
		return
	}
	c.depth++
	if c.depth > c.maxDepth {
		c.maxDepth = c.depth
	}
	c.node(n, "")
	c.depth--
}

func sameNode(a, b *sitter.Node) bool {
	return a != nil && b != nil && a.StartByte() == b.StartByte() && a.EndByte() == b.EndByte()
}

func (c *cogWalk) walkChildren(n *sitter.Node, inh string) {
	for i := uint(0); i < n.NamedChildCount(); i++ {
		c.node(n.NamedChild(i), inh)
	}
}

func (c *cogWalk) walkOthers(n, body *sitter.Node) {
	for i := uint(0); i < n.NamedChildCount(); i++ {
		ch := n.NamedChild(i)
		if sameNode(ch, body) {
			continue
		}
		c.node(ch, "")
	}
}

func (c *cogWalk) node(n *sitter.Node, inh string) {
	if n == nil {
		return
	}
	switch n.Kind() {
	case "function_item", "closure_expression":
		return // separate function unit
	case "if_expression":
		c.cognitive += 1 + c.depth
		c.nest(n.ChildByFieldName("consequence"))
		if alt := n.ChildByFieldName("alternative"); alt != nil {
			c.elseClause(alt)
		}
		c.node(n.ChildByFieldName("condition"), "")
		return
	case "while_expression", "loop_expression", "for_expression":
		c.cognitive += 1 + c.depth
		body := n.ChildByFieldName("body")
		c.nest(body)
		c.walkOthers(n, body)
		return
	case "match_expression":
		c.cognitive += 1 + c.depth
		body := n.ChildByFieldName("body")
		c.nest(body)
		c.walkOthers(n, body)
		return
	case "try_expression":
		c.cognitive++
		c.walkChildren(n, "")
		return
	case "binary_expression":
		op := c.w.binaryOp(n)
		if op == "&&" || op == "||" {
			if op != inh {
				c.logical++
				if cnt := c.boolOperands(n); cnt > c.boolMax {
					c.boolMax = cnt
				}
			}
			inh = op
		} else {
			inh = ""
		}
		c.walkChildren(n, inh)
		return
	case "call_expression":
		if name := c.w.calleeName(n); name != "" {
			c.calls = append(c.calls, name)
			if c.self != "" && name == c.self {
				c.recursion++
			}
		}
		c.walkChildren(n, "")
		return
	}
	c.walkChildren(n, inh)
}

// elseClause handles `else if` (no nesting penalty) vs a plain `else` block.
func (c *cogWalk) elseClause(alt *sitter.Node) {
	var inner *sitter.Node
	for i := uint(0); i < alt.NamedChildCount(); i++ {
		inner = alt.NamedChild(i)
		break
	}
	if inner == nil {
		return
	}
	if inner.Kind() == "if_expression" {
		c.cognitive++
		c.nest(inner.ChildByFieldName("consequence"))
		if a := inner.ChildByFieldName("alternative"); a != nil {
			c.elseClause(a)
		}
		c.node(inner.ChildByFieldName("condition"), "")
		return
	}
	c.cognitive++
	c.nest(inner)
}

func (w *walker) binaryOp(n *sitter.Node) string {
	for i := uint(0); i < n.ChildCount(); i++ {
		ch := n.Child(i)
		if !ch.IsNamed() && ch.ChildCount() == 0 {
			if ch.Kind() == "&&" || ch.Kind() == "||" {
				return ch.Kind()
			}
		}
	}
	return ""
}

func (w *walker) calleeName(n *sitter.Node) string {
	return w.calleeOf(n.ChildByFieldName("function"))
}

func (w *walker) calleeOf(n *sitter.Node) string {
	if n == nil {
		return ""
	}
	switch n.Kind() {
	case "identifier", "field_identifier":
		return w.text(n)
	case "field_expression":
		return w.calleeOf(n.ChildByFieldName("field"))
	case "scoped_identifier":
		return w.calleeOf(n.ChildByFieldName("name"))
	case "generic_function":
		return w.calleeOf(n.ChildByFieldName("function"))
	}
	return ""
}

func (c *cogWalk) boolOperands(n *sitter.Node) int {
	if n == nil || n.Kind() != "binary_expression" {
		return 1
	}
	op := c.w.binaryOp(n)
	if op != "&&" && op != "||" {
		return 1
	}
	left := n.ChildByFieldName("left")
	right := n.ChildByFieldName("right")
	if left == nil && n.NamedChildCount() > 0 {
		left = n.NamedChild(0)
	}
	if right == nil && n.NamedChildCount() > 1 {
		right = n.NamedChild(1)
	}
	return c.boolOperands(left) + c.boolOperands(right)
}

func (w *walker) recordComment(n *sitter.Node) {
	start := startLine(n)
	for i, line := range strings.Split(w.text(n), "\n") {
		if isSignificantComment(line) {
			w.comments[start+i] = true
		}
	}
}

func isSignificantComment(text string) bool {
	for _, r := range text {
		if unicode.IsLetter(r) || unicode.IsDigit(r) {
			return true
		}
	}
	return false
}

func (w *walker) children(n *sitter.Node, fn *lang.Function, typeName string) {
	for i := uint(0); i < n.ChildCount(); i++ {
		c := n.Child(i)
		if c.ChildCount() == 0 {
			w.emitLeaf(c)
			continue
		}
		w.walkNode(c, fn, typeName)
	}
}

func (w *walker) emitLeaf(n *sitter.Node) {
	kind := n.Kind()
	if commentKinds[kind] {
		w.recordComment(n)
		return
	}
	if stringLike[kind] {
		return
	}
	if numberKinds[kind] {
		w.emitToken(lang.Token{Kind: lang.TokNumber, Text: "NUM", Line: startLine(n)})
		return
	}
	t := lang.Token{Line: startLine(n)}
	if nameKinds[kind] {
		t.Kind = lang.TokIdent
		t.Text = w.text(n)
	} else {
		t.Kind = lang.TokKeyword
		t.Text = w.text(n)
	}
	w.emitToken(t)
}

func (w *walker) text(n *sitter.Node) string {
	return string(w.src[n.StartByte():n.EndByte()])
}

func (w *walker) emitToken(t lang.Token) {
	w.res.Tokens = append(w.res.Tokens, t)
	w.lines[t.Line] = true
}

func hasLeafToken(n *sitter.Node, kinds ...string) bool {
	for i := uint(0); i < n.ChildCount(); i++ {
		c := n.Child(i)
		if !c.IsNamed() && c.ChildCount() == 0 {
			for _, k := range kinds {
				if c.Kind() == k {
					return true
				}
			}
		}
	}
	return false
}

func startLine(n *sitter.Node) int { return int(n.StartPosition().Row) + 1 }

func countLines(src []byte) int {
	if len(src) == 0 {
		return 0
	}
	n := strings.Count(string(src), "\n")
	if src[len(src)-1] != '\n' {
		n++
	}
	return n
}
